
from Hurricane import DebugSession

#DebugSession.addToTrace( katana.getCell().getNet( 'ck_ctl' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'dpt_ishifter_muxoutput_156' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'ctl_mbk_buf_seq_mbk_not_ep_87' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'dpt_bar_s_31' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'dpt_opx_out_10' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'dpt_wm_rf_nadw0x' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'dpt_bar_s_20' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'dpt_bar_s_29' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'wenable_5' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'dpt_wm_rf_nadr3x' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'dpt_ad_s_31' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'dpt_wm_rf_adr2x' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'rw_ctl(12)' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'dpt_wm_rf_adr0x' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'dpt_wm_rf_adr3x' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'dpt_wm_rf_nandr0' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'dpt_wm_rf_dinx_0' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'ctlopy_4' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'dpt_ishifter_muxoutput_151' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'ctl_seq_a4_x2_28' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'datain(23)' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'datain(2)' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'ck_dpt' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'dpt_wm_rf_nren' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'ctl_seq_ep_45' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'ctl_seq_mbk_not_ep_98' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'berr' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'dpt_wm_rf_selw_1' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'dpt_dt_s_18' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'dpt_ad_reg_desc_scanx' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'dpt_wm_rf_sel1' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'dpt_wm_rf_sel0' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'test' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'dpt_wm_rf_dinx_0' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'crsrin_0' ) )
# Misaligned VIA @(1809.5L,20L).
#DebugSession.addToTrace( katana.getCell().getNet( 'dpt_dt_reg_desc_nwenx' ) )
# Empty constraint box on <id:183479 ContactTerminal dpt_hi_s_28 VIA12 [1075um 1477.5um] 1um x 1um -T-----c->
#DebugSession.addToTrace( katana.getCell().getNet( 'dpt_hi_s_28' ) )
# Packing error on <id:272860 Vertical dpt_ishifter_muxoutput_79 METAL3 [2990um 765um] [2990um 775um] ...>
#DebugSession.addToTrace( katana.getCell().getNet( 'dpt_ishifter_muxoutput_79' ) )
