
from Hurricane import DebugSession

#DebugSession.addToTrace( katana.getCell().getNet( 'ck_ctl' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'dpt_ishifter_muxoutput_156' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'ctl_mbk_buf_seq_mbk_not_ep_87' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'dpt_bar_s_31' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'dpt_opx_out_10' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'dpt_wm_rf_nadw0x' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'dpt_bar_s_20' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'dpt_bar_s_29' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'wenable_5' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'dpt_wm_rf_nadr3x' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'dpt_ad_s_31' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'dpt_wm_rf_adr2x' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'rw_ctl(12)' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'dpt_wm_rf_adr0x' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'dpt_wm_rf_adr3x' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'dpt_wm_rf_nandr0' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'dpt_wm_rf_dinx_0' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'ctlopy_4' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'dpt_ishifter_muxoutput_151' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'ctl_seq_a4_x2_28' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'datain(23)' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'datain(2)' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'ck_dpt' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'dpt_wm_rf_nren' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'ctl_seq_ep_45' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'ctl_seq_mbk_not_ep_98' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'berr' ) )
