
from coriolis.Hurricane import DebugSession

#DebugSession.addToTrace( katana.getCell().getNet( 'A(5)' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'abc_11873_new_n338' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'MOS6502_IRHOLD_valid' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'abc_11873_new_n1137' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'MOS6502_op(3)' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'clk_root_bl_0' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'abc_11867_new_n1489' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'abc_11867_new_n956' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'abc_11867_new_n436' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'abc_11867_new_n1273' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'RDY' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'abc_11867_new_n1399' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'MOS6502_op(2)' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'abc_11867_new_n326' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'abc_11867_auto_rtlil_cc_2608_MuxGate_11856' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'abc_11867_new_n1448' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'abc_11867_auto_rtlil_cc_2608_MuxGate_11704' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'MOS6502_shift' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'MOS6502_DIMUX(7)' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'abc_11867_new_n1201' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'abc_11867_new_n1202' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'abc_11867_new_n377' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'MOS6502_shift' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'abc_11867_new_n1204' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'abc_11867_new_n1338' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'DI(4)' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'MOS6502_op(3)' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'abc_11867_new_n1476' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'abc_11867_new_n1449' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'abc_11867_new_n1433' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'MOS6502_ABL(6)' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'abc_11867_new_n393' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'abc_11867_new_n996' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'abc_11867_new_n566' ) )
# (73um,118um) id:89120
#DebugSession.addToTrace( katana.getCell().getNet( 'abc_11867_new_n374' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'abc_11867_new_n1008' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'abc_11867_auto_rtlil_cc_2608_MuxGate_11836' ) )
