# -*- explicit-buffer-name: "Makefile<alliance-check-toolkit/nsxlib>" -*-

           LIBRARY_FAMILY = nsxlib

 include ../../etc/rules.mk


#check-lib: ./check/inv_x1.ok \
#           ./check/sff1_x4.ok
