
from coriolis.Hurricane import DebugSession

#DebugSession.addToTrace( katana.getCell().getNet( 'rsdnbr_sd(16)' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'hz_tdm_sd' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'ck' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'mips_r3000_1m_dp_badr_sd(31)' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'mips_r3000_1m_dp_otheri_sd(0)' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'wreg_sw(4)' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'mips_r3000_1m_dp_xor_se(0)' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'mips_r3000_1m_dp_banc_dinx(10)' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'wreg_sw(13)' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'wreg_sw(14)' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'mips_r3000_1m_dp_shift32_rshift_se_c0(2)' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'mips_r3000_1m_ct_not_hold_si)' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'mips_r3000_1m_dp_shift32_rshift_se_muxoutput(112)' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'mips_r3000_1m_dp_res_re(30)' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'mips_r3000_1m_dp_yoper_se(4)' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'mips_r3000_1m_dp_nextpc_rd(0)' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'mips_r3000_1m_dp_banc_dinx(27)' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'rsdnbr_sd(22)' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'mips_r3000_1m_ct_bdslot_rd' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'rtdnbr_sd(21)' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'mips_r3000_1m_dp_banc_dinx(31)' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'rtdnbr_sd(2)' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'mips_r3000_1m_dp_mux32_s_mw_se_sel0' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'rtdnbr_sd(11)' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'wreg_sw(11)' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'rtdnbr_sd(12)' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'rtdnbr_sd(15)' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'mips_r3000_1m_dp_shift32_rshift_se_msb' ) )
