
from Hurricane import DebugSession

#DebugSession.addToTrace( katana.getCell().getNet( 'arm_core_i.decod_i.wadr2(3)' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'arm_core_i.decod_i.wdata2(17)' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'arm_core_i.decod_i.reg_bank.not_r_valid(13)' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'arm_core_i.decod_i.decod_inst.not_aux188' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'arm_core_i.decod_i.wadr1(1)' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'arm_core_i.decod_i.wadr2(1)' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'arm_core_i.decod_i.reg_bank.not_inval_adr1(0)' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'arm_core_i.decod_i.reg_bank.r_r10(22)' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'arm_core_i.decod_i.wadr2(2)' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'arm_core_i.decod_i.wadr1(1)' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'arm_core_i.decod_i.wadr1(2)' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'arm_core_i.decod_i.reg_bank.not_inval_adr2(2)' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'arm_core_i.decod_i.reg_bank.na3_x1_305_sig' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'arm_core_i.decod_i.reg_bank.ao22_x2_182_sig' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'arm_core_i.decod_i.reg_bank.oa2ao222_x2_493_sig' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'arm_core_i.decod_i.reg_bank.not_p446_6_def_56' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'arm_core_i.decod_i.reg_bank.not_wadr2(2)' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'core.decod_i.reg_bank.not_p446_6_def_49' ) )
