
from coriolis.Hurricane import DebugSession

#DebugSession.addToTrace( katana.getCell().getNet( 'dat_o_to_pad(0)' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'core.registers_m_operand1(14)' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'core.registers_m_address(19)' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'core.registers_m_operand1(1)' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'core.registers_m_operand1(11)' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'core.registers_m_pc_valid(18)' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'core.registers_m_pc_valid(1)' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'core.registers_m_pc_valid(26)' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'core.registers_m_address(18)' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'core.abc_75177_new_n3243_hfns_2' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'core.flatten_alu_m_procmux_3373_y(1)' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'core.registers_m_operand1(11)' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'core.registers_m_operand1(11)' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'core.memory_registers_m_dn_output(4)' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'core.flatten_alu_m_procmux_3373_y(7)' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'core.registers_m_data_write(20)' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'dat_i_from_pad(24)' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'core.auto_dfflegalize_cc_346_handle_ff_75107_hfns_0' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'core.alu_m_result_bit10_hfns_0' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'core.alu_m_result(11)' ) )
