# -*- explicit-buffer-name: "Makefile<alliance-check-toolkit/ISPD05/bigblue1>" -*-

                     CHIP = bigblue1
            USE_SYNTHESIS = No
                USE_DEBUG = No


 include ../../etc/rules.mk

all:  ispd
ispd: ispd-bigblue1 
