# -*- explicit-buffer-name: "Makefile<alliance-check-toolkit/lsxlib>" -*-

 PHYSICAL_SYNTHESIS = Alliance
         DESIGN_KIT = lsxlib

 include ./mk/design-flow.mk
 include ./mk/check-library.mk


export MBK_CATA_LIB = $(CELLS_TOP)/lsxlib


characterize: lsxlib-dot-lib


check-lib-test: ./check/inv_x1.ok\
				./check/a2_x2.ok \
				./check/a2_x4.ok \
				./check/a3_x2.ok \
				./check/a3_x4.ok \
				./check/a4_x2.ok \
				./check/a4_x4.ok \
				./check/an12_x1.ok \
				./check/an12_x4.ok \
				./check/ao22_x2.ok \
				./check/ao22_x4.ok \
				./check/ao2o22_x2.ok \
				./check/ao2o22_x4.ok \
				./check/buf_x2.ok \
				./check/buf_x4.ok \
				./check/buf_x8.ok \
				./check/inv_x1.ok \
				./check/inv_x2.ok \
				./check/inv_x4.ok \
				./check/inv_x8.ok \
				./check/mx2_x2.ok \
				./check/mx2_x4.ok \
				./check/mx3_x2.ok \
				./check/mx3_x4.ok \
				./check/na2_x1.ok \
				./check/na2_x4.ok \
				./check/na3_x1.ok \
				./check/na3_x4.ok \
				./check/na4_x1.ok \
				./check/na4_x4.ok \
				./check/nao22_x1.ok \
				./check/nao22_x4.ok \
				./check/nao2o22_x1.ok \
				./check/nao2o22_x4.ok \
				./check/nmx2_x1.ok \
				./check/nmx2_x4.ok \
				./check/nmx3_x1.ok \
				./check/nmx3_x4.ok \
				./check/no2_x1.ok \
				./check/no2_x4.ok \
				./check/no3_x1.ok \
				./check/no3_x4.ok \
				./check/no4_x1.ok \
				./check/no4_x4.ok \
				./check/noa22_x1.ok \
				./check/noa22_x4.ok \
				./check/noa2a22_x1.ok \
				./check/noa2a22_x4.ok \
				./check/noa2a2a23_x1.ok \
				./check/noa2a2a23_x4.ok \
				./check/noa2a2a2a24_x1.ok \
				./check/noa2a2a2a24_x4.ok \
				./check/noa2ao222_x1.ok \
				./check/noa2ao222_x4.ok \
				./check/noa3ao322_x1.ok \
				./check/noa3ao322_x4.ok \
				./check/nts_x1.ok \
				./check/nts_x2.ok \
				./check/nxr2_x1.ok \
				./check/nxr2_x4.ok \
				./check/o2_x2.ok \
				./check/o2_x4.ok \
				./check/o3_x2.ok \
				./check/o3_x4.ok \
				./check/o4_x2.ok \
				./check/o4_x4.ok \
				./check/oa22_x2.ok \
				./check/oa22_x4.ok \
				./check/oa2a22_x2.ok \
				./check/oa2a22_x4.ok \
				./check/oa2a2a23_x2.ok \
				./check/oa2a2a23_x4.ok \
				./check/oa2a2a2a24_x2.ok \
				./check/oa2a2a2a24_x4.ok \
				./check/oa2ao222_x2.ok \
				./check/oa2ao222_x4.ok \
				./check/oa3ao322_x2.ok \
				./check/oa3ao322_x4.ok \
				./check/on12_x1.ok \
				./check/on12_x4.ok \
				./check/one_x0.ok \
				./check/rowend_x0.ok \
				./check/sff1_x4.ok \
				./check/sff2_x4.ok \
				./check/sff3_x4.ok \
				./check/ts_x4.ok \
				./check/ts_x8.ok \
				./check/xr2_x1.ok \
				./check/xr2_x4.ok \
				./check/zero_x0.ok

check-clean: ; rm -f ./check/*
