# -*- explicit-buffer-name: "Makefile<alliance-check-toolkit/AM2901>" -*-

                     CORE = coeur
                     CHIP = amd2901
                   MARGIN = 2
        GENERATE_CORE_VST = No
                USE_MOSIS = No
                USE_DEBUG = Yes

 include ../etc/rules.mk

 export         MBK_IN_LO = vst
 export        MBK_OUT_LO = vst
 export            RDS_IN = gds
 export           RDS_OUT = gds


all: $(ALLIANCE_CHIP).gds

