# -*- explicit-buffer-name: "Makefile<alliance-check-toolkit/adder/alliance>" -*-

                     CHIP = chip
                     CORE = adder
                   MARGIN = 2
                  BOOMOPT =
                  BOOGOPT =
                  LOONOPT =
                NSL2VHOPT = -vasy
          USE_ALLIANCE_PR = Yes
            USE_SYNTHESIS = Alliance
            USE_CLOCKTREE = No
           LIBRARY_FAMILY = nsxlib
                USE_DEBUG = No

                 NETLISTS = adder

 include ../../etc/rules.mk


lvx:         lvx-chip
druc:        druc-chip
dreal:       dreal-chip
flatph:      flatph-chip
view:        cgt-chip

layout:      chip.ap
gds:         chip.gds
gds_flat:    chip_flat.gds
cif:         chip.cif
