# -*- explicit-buffer-name: "Makefile<alliance-check-toolkit/nsxlib>" -*-

                  TK_RTOP = ../..
 export      MBK_CATA_LIB = $(TOOLKIT_CELLS_TOP)/phlib

 include $(TK_RTOP)/etc/mk/alliance.mk
 include $(TK_RTOP)/etc/mk/phenitec.mk
 include $(TK_RTOP)/etc/mk/check-library.mk


 characterize: phlib-dot-lib

 type_env:
	echo "RDS=" $(RDS_TECHNO_NAME)


#check-lib: ./check/inv_x1.ok \
#           ./check/sff1_x4.ok
