
from Hurricane import DebugSession

#DebugSession.addToTrace( katana.getCell().getNet( 'p_reset' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'm_clock' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'abc_5360_n903_1' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'memory_adr' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'mstore' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'iadrs(9)' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'abc_5360_n469_1' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'abc_5360_n478_1' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'abc_5360_n484_1' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'subckt_892_reg4.abc_5081_n421' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'subckt_892_reg4.abc_5081_n250' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'subckt_892_reg4.abc_5081_n370' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'abc_5478_n584_1' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'abc_5478_n1139' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'cr2(13)' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'abc_5478_n546_1' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'abc_5478_n701_1' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'abc_5478_n594_1' ) )
