from Hurricane import DebugSession

#DebugSession.addToTrace( katana.getCell().getNet( 'cu_issue_i' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'cu_wr_rel_o(2)' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'xer_so_ok' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'core.soc_cpu_minerva_gprf_mem_mem_rdreg_0_d_30' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'core.soc_cpu_minerva_gprf_mem_mem_rdreg_1_d_7' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'core.soc_cpu_minerva_gprf_mem_mem_rdreg_1_d_0' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'core.abc_109444_new_n19819' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'core.abc_109444_new_n51961' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'io_in_from_pad_bit0_root_tr_tr_tl_tl_2' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'io_in_from_pad_bit0_root_br_tl_tr_tr_0' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'core.abc_109444_new_n34872' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'core.abc_109444_new_n25771' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'core.abc_109444_new_n43572' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'core.abc_109444_new_n25283' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'core.abc_109383_new_n22472' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'core.abc_109383_new_n19826' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'io_in_from_pad(6)' ) )
