
from Hurricane import DebugSession

#DebugSession.addToTrace( katana.getCell().getNet( 'core.result(1)' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'core.result(58)' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'core.result(12)' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'core.result(56)' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'f_to_pad(3)' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'we_from_pad(0)' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'a_from_pad(2)' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'core.result(0)' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'a_from_pad(6)' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'a_from_pad(1)' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'core.result(16)' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'byte_out_to_pad(0)' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'core.q_29' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'core.abc_1471_new_n218' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'core.q_26' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'core.q_5' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'core.q_31' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'byte_out_to_pad(2)' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'rst_from_pad' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'a_from_pad(2)' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'core.result(33)' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'clk_from_pad' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'byte_out_to_pad(3)' ) )
