# -*- explicit-buffer-name: "Makefile<alliance-check-toolkit/cpu>" -*-

                   MARGIN = 2
                  BOOMOPT = -A
                  BOOGOPT =
                  LOONOPT =
                NSL2VHOPT = -vasy
            USE_SYNTHESIS = Alliance
            USE_CLOCKTREE = Yes
           LIBRARY_FAMILY = nsxlib
                USE_DEBUG = No

                 NETLISTS = cpu

 include ../etc/rules.mk

lvx:       lvx-chip_clocked_kite
druc:      druc-chip_clocked_kite
view:      cgt-view-chip_clocked_kite

layout:    chip_clocked_kite.ap
gds:       chip_clocked_kite.gds
