#!/bin/bash

 cells=""
 cells="${cells} a2_x2.vhdl"
 cells="${cells} a3_x2.vhdl"
 cells="${cells} a4_x2.vhdl"
 cells="${cells} ao22_x2.vhdl"
 cells="${cells} buf_x1.vhdl"
 cells="${cells} buf_x2.vhdl"
 cells="${cells} buf_x4.vhdl"
 cells="${cells} decap_w0.vhdl"
 cells="${cells} diode_w1.vhdl"
 cells="${cells} fill.vhdl"
 cells="${cells} fill_w2.vhdl"
 cells="${cells} fill_w4.vhdl"
 cells="${cells} inv_x0.vhdl"
 cells="${cells} inv_x1.vhdl"
 cells="${cells} inv_x2.vhdl"
 cells="${cells} inv_x4.vhdl"
 cells="${cells} mx2_x2.vhdl"
 cells="${cells} mx3_x2.vhdl"
 cells="${cells} nand2_x0.vhdl"
 cells="${cells} nand3_x0.vhdl"
 cells="${cells} nand4_x0.vhdl"
 cells="${cells} nor2_x0.vhdl"
 cells="${cells} nor3_x0.vhdl"
 cells="${cells} nor4_x0.vhdl"
 cells="${cells} nsnrlatch_x1.vhdl"
 cells="${cells} nxr2_x1.vhdl"
 cells="${cells} o2_x2.vhdl"
 cells="${cells} o3_x2.vhdl"
 cells="${cells} o4_x2.vhdl"
 cells="${cells} oa22_x2.vhdl"
 cells="${cells} one_x1.vhdl"
 cells="${cells} powmid_x0.vhdl"
 cells="${cells} sff1r_x4.vhdl"
 cells="${cells} sff1_x4.vhdl"
 cells="${cells} tie_diff.vhdl"
 cells="${cells} tie_diff_w2.vhdl"
 cells="${cells} tie_diff_w4.vhdl"
 cells="${cells} tie_poly.vhdl"
 cells="${cells} tie_poly_w2.vhdl"
 cells="${cells} tie_poly_w4.vhdl"
 cells="${cells} tie.vhdl"
 cells="${cells} tie_w2.vhdl"
 cells="${cells} tie_w4.vhdl"
 cells="${cells} xr2_x1.vhdl"
 cells="${cells} zeroone_x1.vhdl"
 cells="${cells} zero_x1.vhdl"

 echo "Converting cell from VHDL to Alliance VBE."
 export MBK_CATA_LIB=.
 rm -f ./CATAL
 for cell in ${cells}; do
   echo "- ${cell}"
   stem=`basename ${cell} .vhdl`
   vasy -I vhdl -a ${cell} ${stem}

   echo "${stem}  C" >> ./CATAL
 done
