# -*- explicit-buffer-name: "Makefile<alliance-check-toolkit/sxlib>" -*-
#
# Smart HTTP commit test #1

                  TK_RTOP = ../..
 export      MBK_CATA_LIB = $(TOOLKIT_CELLS_TOP)/sxlib

 include $(TK_RTOP)/etc/mk/alliance.mk
 include $(TK_RTOP)/etc/mk/binaries.mk
#include $(TK_RTOP)/etc/mk/phenitec.mk
#include $(TK_RTOP)/etc/mk/mosis.mk
 include $(TK_RTOP)/etc/mk/cmos.mk
 include $(TK_RTOP)/etc/mk/check-library.mk


 characterize: sxlib-dot-lib


#check-lib: ./check/inv_x1.ok \
#           ./check/sff1_x4.ok
