# -*- explicit-buffer-name: "Makefile<alliance-check-toolkit/cpu/alliance>" -*-

                     CHIP = chip
                     CORE = cpu
                   MARGIN = 2
                  BOOMOPT = -A
                  BOOGOPT =
                  LOONOPT =
                NSL2VHOPT = -vasy
          USE_ALLIANCE_PR = Yes
            USE_SYNTHESIS = Alliance
           LIBRARY_FAMILY = nsxlib
                USE_DEBUG = No

                 NETLISTS = cpu.vst

 include ../../etc/rules.mk

lvx:       lvx-chip
druc:      druc-chip
view:      cgt-chip

layout:    chip.ap
gds:       chip.gds
