# -*- explicit-buffer-name: "Makefile<alliance-check-toolkit/sxlib_25um>" -*-

                  TK_RTOP = ../../..
 export      MBK_CATA_LIB = $(TOOLKIT_CELLS_TOP)/hibikino/sxlib_25um

 include $(TK_RTOP)/etc/mk/alliance.mk
 include $(TK_RTOP)/etc/mk/hibikino.mk
 include $(TK_RTOP)/etc/mk/check-library.mk


 characterize: sxlib_25um-dot-lib


#check-lib: ./check/inv_x1.ok \
#           ./check/sff1_x4.ok
