# -*- explicit-buffer-name: "Makefile<alliance-check-toolkit/MIPS/microprogrammed>" -*-

            USE_SYNTHESIS = No
            USE_CLOCKTREE = No
                USE_DEBUG = No

                 NETLISTS = mips_r3000_1m_core_flat

 include ../../etc/rules.mk

lvx:     lvx-mips_r3000_1m_core_flat_kite
druc:    druc-mips_r3000_1m_core_flat_kite
view:    cgt-mips_r3000_1m_core_flat_kite

layout:  mips_r3000_1m_core_flat_kite.ap
gds:     mips_r3000_1m_core_flat_kite.gds

