# -*- explicit-buffer-name: "Makefile<alliance-check-toolkit/MIPS/microprogrammed>" -*-

                  TK_RTOP = ../..

            USE_CLOCKTREE = No
                USE_DEBUG = No

 include $(TK_RTOP)/etc/mk/alliance.mk
 include $(TK_RTOP)/etc/mk/sxlib.mk
 include $(TK_RTOP)/etc/mk/synthesis-disabled.mk
 include $(TK_RTOP)/etc/mk/pr-coriolis.mk


lvx:     lvx-mips_r3000_1m_core_flat_kite
druc:    druc-mips_r3000_1m_core_flat_kite
view:    cgt-mips_r3000_1m_core_flat_kite

layout:  mips_r3000_1m_core_flat_kite.ap
gds:     mips_r3000_1m_core_flat_kite.gds

