
from Hurricane import DebugSession

#DebugSession.addToTrace( katana.getCell().getNet( 'subckt_0_cpu.abc_10753_n1000' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'subckt_0_cpu.abh(1)' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'subckt_0_cpu.abc_10753_n356' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'subckt_0_cpu.abc_10753_n1342' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'subckt_0_cpu.n0_sei_0_0' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'subckt_0_cpu.abc_10753_n354' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'subckt_0_cpu.abc_10753_n829_1' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'subckt_0_cpu.abc_10753_n368' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'subckt_0_cpu.pc(12)' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'subckt_0_cpu.abc_10753_n981' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'subckt_0_cpu.abc_10753_n1333' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'subckt_0_cpu.abc_10753_n1261' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'subckt_0_cpu.abc_10753_n681' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'subckt_0_cpu.subckt_1302_alu.abc_10572_n84' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'subckt_0_cpu.alu_op(0)' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'subckt_0_cpu.n0_sei_0_0' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'subckt_0_cpu.abc_10753_n1304' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'subckt_0_cpu.abc_10753_n592' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'subckt_0_cpu.abc_10753_n356' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'subckt_0_cpu.abc_10753_n688_1' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'subckt_0_cpu.abc_10753_n1097_1' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'subckt_0_cpu.n0_sec_0_0' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'subckt_0_cpu.abc_10753_n515' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'subckt_0_cpu.abc_10753_n1259_1' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'subckt_0_cpu.abc_10753_n1332' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'subckt_0_cpu.abc_10753_n1428' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'subckt_0_cpu.abc_10753_n484' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'subckt_0_cpu.adc_bcd' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'subckt_0_cpu.abc_10753_n594' ) )

#DebugSession.addToTrace( katana.getCell().getNet( 'subckt_0_cpu.abc_10753_n1333' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'subckt_0_cpu.adc_sbc' ) )

#DebugSession.addToTrace( katana.getCell().getNet( 'subckt_0_cpu.abc_10753_n1004' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'subckt_0_cpu.abc_10753_n1376' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'subckt_0_cpu.abc_10753_n471' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'subckt_0_cpu.abh(1)' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'subckt_0_cpu.add(1)' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'subckt_0_cpu.dimux(6)' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'subckt_0_cpu.axys_1_3' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'subckt_0_cpu.abc_10753_n337' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'subckt_0_cpu.abc_10753_n980' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'subckt_0_cpu.dimux(7)' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'subckt_0_cpu.axys_0_3' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'subckt_0_cpu.abc_10753_n338' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'subckt_0_cpu.abc_10753_n360' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'subckt_0_cpu.ai(5)' ) )
