# -*- explicit-buffer-name: "Makefile<MIPS/microprogrammed>" -*-


       PHYSICAL_SYNTHESIS = Coriolis
               DESIGN_KIT = sxlib

            USE_CLOCKTREE = No
                USE_DEBUG = No
               USE_KATANA = Yes

 include ./mk/design-flow.mk


layout:  mips_core_flat_r.ap
gds:     mips_core_flat_r.gds

lvx:     lvx-mips_core_flat_r
druc:    druc-mips_core_flat_r
view:    cgt-mips_core_flat_r
