# -*- explicit-buffer-name: "Makefile<alliance-check-toolkit/adder>" -*-

                     CHIP = chip
                   MARGIN = 2
                  BOOMOPT =
                  BOOGOPT =
                  LOONOPT =
                NSL2VHOPT = -vasy
            USE_SYNTHESIS = Yes
            USE_CLOCKTREE = No
           LIBRARY_FAMILY = msxlib
                USE_DEBUG = No

                 NETLISTS = adder

 include ../etc/rules.mk


lvx:         lvx-chip_kite
druc:        druc-chip_kite
dreal:       dreal-chip_kite
flatph:      flatph-chip_kite
view:        cgt-chip_kite

layout:      chip_kite.ap
gds:         chip_kite.gds
gds_flat:    chip_kite_flat.gds
cif:         chip_kite.cif
