# -*- explicit-buffer-name: "Makefile<alliance-check-toolkit/adder>" -*-

                     CORE = adder
                     CHIP = chip
                   MARGIN = 2
                  BOOMOPT =
                  BOOGOPT =
                  LOONOPT =
                NSL2VHOPT = -vasy
        GENERATE_CORE_VST = Yes
                USE_MOSIS = Yes
                USE_DEBUG = Yes

 include ../etc/rules.mk

 export         MBK_IN_LO = vst
 export        MBK_OUT_LO = vst
 export            RDS_IN = gds
 export           RDS_OUT = gds


all: $(ALLIANCE_CHIP).gds

