from coriolis.Hurricane import DebugSession

#DebugSession.addToTrace( katana.getCell().getNet( 'Vout+' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'vb5' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'ampp_71' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'ampn_72' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'ampp_73' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'ampn_72' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'ampn_4' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'ampp_4' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'm2n_in' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'm2p_in' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'm2n_in' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'ampp_61' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'ampn_61' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'ampp_2' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'm4an_in' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'vcmfb' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'alim' ) )
