
from coriolis.Hurricane import DebugSession

#DebugSession.addToTrace( katana.getCell().getNet( 'ionet1181' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'ionet11' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'ionet1117' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'net7298' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'net1811' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'net1224' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'net16498' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'ionet167' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'ionet58' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'net29936' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'net30916' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'net28198' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'net26103' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'ionet122' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'net11241' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'net8220' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'net5' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'net4562' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'net223' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'net24738' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'net3005' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'net10279' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'net30020' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'net3188' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'ionet1146' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'net9633' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'net6640' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'net7223' ) )
#DebugSession.addToTrace( katana.getCell().getNet( 'ionet1005' ) )

